### ISSUE TITLE
Scroll not working when hovering elements with position:absolute

### ISSUE THREAD

**Issue by WiS3** [noeldelgado/gemini-scrollbar#30]
Hello, i have a div `#contentWrapper` with `position:relative`, the scrollbar is attached to this element and it is working fine, but inside i have some elements with `position:absolute`, and the scrolling doesn't work when the mouse is over those elements.
The native scrolling is working, but not with gm.

How i can solve this issue? Thanks

**Comment by noeldelgado** [comment]
Hi @WiS3, can you please create a "bin" reproducing the problem?, you can use this one as a starting point http://requirebin.com/?gist=300eb3d11e731561815ceb088786815f, thanks.

**Comment by lianyzhou** [comment]
i have the same problems

**Comment by noeldelgado** [comment]
Hi @WiS3, @lianyzhou. I just tried that really quick and I am getting the same behaviour for both cases (not being able to scroll when hovering those elements). - http://requirebin.com/?gist=300eb3d11e731561815ceb088786815f

With that, I don't think it is a library problem, but the expected behaviour.

Tested on OS X Yosemite v10.10.3
* Firefox 47.0
* Chrome 51.0.2704.103
* Opera 38.0.2220.41

If you are sure this is a library problem, please provide more information (or update the "bin") so I can continue debugging.

Thanks.

**Comment by noeldelgado** [comment]
@WiS3, @lianyzhou: Btw, if your `absolute` elements are for pure decoration, try adding `pointer-events: none` to them. Let me know if that works for you.
