### ISSUE TITLE
Thumb hasn't min height

### ISSUE THREAD

**Issue by vlukyanoff** [noeldelgado/gemini-scrollbar#41]
If there lots of elements in scrollable view, thumb is very small

**Comment by noeldelgado** [comment]
Hi @vlukyanoff, I just published a new version (v1.5.0) which adds a new config option `minThumbSize`, its default value is `20`(px) [941455b].

Please let me know if that works for you.

Cheers.

**Comment by vlukyanoff** [comment]
Hi @noeldelgado, I tested version 1.5.0, it works how I expected, thanks a lot!

Could you update dependency to v1.5.0 in https://github.com/noeldelgado/react-gemini-scrollbar ?

**Comment by noeldelgado** [comment]
Hi Viacheslav, thanks for testing!

There is one thing I have to make sure before I update the dependency on react-gemini... in version 1.4.x of gemini it was introduced a feature which modifies the DOM structure (which as far as I remember, react does not like that at all), I think you can reproduce the issue by using the new version and appending new elements to the scroll-content dynamically, that will result in reseting the scroll position to zero... I will try to test if the issue is not happening anymore or fix it before I upgrade the dependency version.

Thanks for your help!

**Comment by noeldelgado** [comment]
updated
